-- PaCELab Equip — Postgres schema.
--
-- Translated from the SQLite schema that shipped in data/lab.sqlite. The aim
-- here is a faithful translation, not an improved one: anything that changes
-- how a value behaves is listed in Migration/README.md and left for a
-- separate, separately tested change. A migration that also alters semantics
-- gives you no way to tell which half caused a difference.
--
-- What did change, because it had to:
--   INTEGER PRIMARY KEY AUTOINCREMENT  ->  integer GENERATED BY DEFAULT AS IDENTITY
--     BY DEFAULT rather than ALWAYS, so the loader can insert the existing
--     ids and keep every foreign key pointing where it did.
--   SQLite's loose typing          ->  real types. Every DATE column was
--     checked first: all values are ISO or null, so the cast is safe.
--
-- Create order follows the foreign keys.

BEGIN;

CREATE TABLE units (
  unit_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code      text    NOT NULL,
  name      text    NOT NULL DEFAULT '',
  active    integer NOT NULL DEFAULT 1
);

CREATE TABLE labs (
  lab_id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                   text    NOT NULL UNIQUE,
  name                   text    NOT NULL,
  description            text    NOT NULL DEFAULT '',
  unit_id                integer REFERENCES units(unit_id),
  lab_group_name         text    NOT NULL DEFAULT '',
  lab_group_email        text    NOT NULL DEFAULT '',
  equipment_contact_name text    NOT NULL DEFAULT '',
  equipment_contact_email text   NOT NULL DEFAULT '',
  equipment_contact_cc   text    NOT NULL DEFAULT '',
  active                 integer NOT NULL DEFAULT 1,
  created_at             text    NOT NULL
);

CREATE TABLE grants (
  grant_id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lab_id                 integer NOT NULL REFERENCES labs(lab_id),
  cfopa                  text    NOT NULL,
  cfopa_base             text    NOT NULL DEFAULT '',
  activity_code          text    NOT NULL DEFAULT 'A00',
  title                  text    NOT NULL DEFAULT '',
  display_label          text    NOT NULL DEFAULT '',
  principal_investigator text    NOT NULL DEFAULT '',
  unit_id                integer REFERENCES units(unit_id),
  start_date             date,
  end_date               date,
  active                 integer NOT NULL DEFAULT 1,
  created_at             text    NOT NULL
);

CREATE TABLE equipment (
  equipment_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_tag         text    NOT NULL DEFAULT '',
  equip_class          text    NOT NULL DEFAULT 'instrument',
  name                 text    NOT NULL,
  manufacturer         text    NOT NULL DEFAULT '',
  model                text    NOT NULL DEFAULT '',
  location             text    NOT NULL DEFAULT '',
  rate                 double precision NOT NULL DEFAULT 0,
  rate_unit            text    NOT NULL DEFAULT 'per sample',
  rate_effective_date  date,
  receiving_subaccount text    NOT NULL DEFAULT '',
  contact_person       text    NOT NULL DEFAULT '',
  active               integer NOT NULL DEFAULT 1,
  created_at           text    NOT NULL,
  status               text    NOT NULL DEFAULT 'available',
  status_note          text    NOT NULL DEFAULT '',
  status_since         text,
  service_due_date     date,
  lab_id               integer REFERENCES labs(lab_id)
);

CREATE TABLE lab_members (
  member_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lab_id       integer NOT NULL REFERENCES labs(lab_id),
  person_key   text    NOT NULL,
  display_name text    NOT NULL DEFAULT '',
  created_at   text    NOT NULL,
  UNIQUE (lab_id, person_key)
);

CREATE TABLE equipment_costs (
  cost_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_id    integer NOT NULL REFERENCES equipment(equipment_id),
  cost_date       date    NOT NULL,
  category        text    NOT NULL DEFAULT 'consumable',
  description     text    NOT NULL DEFAULT '',
  vendor          text    NOT NULL DEFAULT '',
  amount          double precision NOT NULL DEFAULT 0,
  paid_from_cfopa text    NOT NULL DEFAULT '',
  reference       text    NOT NULL DEFAULT '',
  covers_start    date,
  covers_end      date,
  notes           text    NOT NULL DEFAULT '',
  created_at      text    NOT NULL,
  created_by      text    NOT NULL DEFAULT ''
);

CREATE TABLE export_batches (
  batch_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_start date    NOT NULL,
  period_end   date    NOT NULL,
  generated_at text    NOT NULL,
  generated_by text    NOT NULL DEFAULT '',
  record_count integer NOT NULL DEFAULT 0,
  total_amount double precision NOT NULL DEFAULT 0,
  reopened     integer NOT NULL DEFAULT 0,
  lab_id       integer REFERENCES labs(lab_id)
);

CREATE TABLE usage_records (
  usage_id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_id         integer NOT NULL REFERENCES equipment(equipment_id),
  grant_id             integer NOT NULL REFERENCES grants(grant_id),
  operator_name        text    NOT NULL DEFAULT '',
  use_date             date    NOT NULL,
  sample_count         integer NOT NULL DEFAULT 1,
  rate_charged         double precision NOT NULL DEFAULT 0,
  rate_unit_charged    text    NOT NULL DEFAULT '',
  receiving_subaccount text    NOT NULL DEFAULT '',
  total_charge         double precision NOT NULL DEFAULT 0,
  batch_identifier     text    NOT NULL DEFAULT '',
  notes                text    NOT NULL DEFAULT '',
  exported             integer NOT NULL DEFAULT 0,
  export_batch_id      integer REFERENCES export_batches(batch_id),
  voided               integer NOT NULL DEFAULT 0,
  void_reason          text    NOT NULL DEFAULT '',
  created_at           text    NOT NULL
);

CREATE TABLE reservations (
  reservation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_id   integer NOT NULL REFERENCES equipment(equipment_id),
  reserved_by    text    NOT NULL DEFAULT '',
  start_datetime text    NOT NULL,
  end_datetime   text    NOT NULL,
  purpose        text    NOT NULL DEFAULT '',
  usage_id       integer REFERENCES usage_records(usage_id),
  created_at     text    NOT NULL
);

CREATE TABLE email_log (
  email_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   text    NOT NULL,
  created_by   text    NOT NULL DEFAULT '',
  purpose      text    NOT NULL DEFAULT '',
  to_address   text    NOT NULL DEFAULT '',
  cc_address   text    NOT NULL DEFAULT '',
  subject      text    NOT NULL DEFAULT '',
  body         text    NOT NULL DEFAULT '',
  equipment_id integer REFERENCES equipment(equipment_id),
  opened_at    text,
  status       text    NOT NULL DEFAULT 'composed',
  lab_id       integer REFERENCES labs(lab_id)
);

CREATE TABLE admin_users (
  user_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      text    NOT NULL UNIQUE,
  password_hash text    NOT NULL,
  display_name  text    NOT NULL DEFAULT '',
  active        integer NOT NULL DEFAULT 1,
  created_at    text    NOT NULL,
  last_login    text,
  may_edit_code integer NOT NULL DEFAULT 0
);

CREATE TABLE login_attempts (
  attempt_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip           text    NOT NULL DEFAULT '',
  username     text    NOT NULL DEFAULT '',
  succeeded    integer NOT NULL DEFAULT 0,
  attempted_at text    NOT NULL
);

CREATE TABLE picklists (
  picklist_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_key    text    NOT NULL,
  code        text    NOT NULL,
  label       text    NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  active      integer NOT NULL DEFAULT 1,
  protected   integer NOT NULL DEFAULT 0,
  UNIQUE (list_key, code)
);

-- "key" is quoted because it reads as a keyword even where Postgres allows it
-- unquoted; the application's SQL quotes it too.
CREATE TABLE settings (
  "key" text PRIMARY KEY,
  value text NOT NULL DEFAULT ''
);

-- Indexes, carried across as they were. The partial unique index on
-- property_tag relies on Postgres supporting a WHERE clause on an index,
-- which it does.
CREATE INDEX idx_attempts_time ON login_attempts (attempted_at);
CREATE INDEX idx_costs_equipment ON equipment_costs (equipment_id, cost_date);
CREATE INDEX idx_email_log_lab ON email_log (lab_id, created_at DESC);
CREATE INDEX idx_email_log_time ON email_log (created_at DESC);
CREATE INDEX idx_equipment_lab ON equipment (lab_id, active);
CREATE UNIQUE INDEX idx_equipment_tag ON equipment (property_tag) WHERE property_tag <> '';
CREATE INDEX idx_grants_base ON grants (cfopa_base);
CREATE UNIQUE INDEX idx_grants_lab_cfopa ON grants (lab_id, cfopa);
CREATE INDEX idx_lab_members_key ON lab_members (person_key);
CREATE INDEX idx_reservations_equipment_end ON reservations (equipment_id, end_datetime);
CREATE INDEX idx_reservations_equipment_start ON reservations (equipment_id, start_datetime);
CREATE INDEX idx_usage_equipment ON usage_records (equipment_id);
CREATE INDEX idx_usage_exported ON usage_records (exported, voided);
CREATE INDEX idx_usage_grant ON usage_records (grant_id);
CREATE INDEX idx_usage_use_date ON usage_records (use_date);

COMMIT;
